name: Node.js CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  html-css-js-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run HTMLHint
        run: npx htmlhint '**/*.html'
      - name: Run Stylelint
        run: npx stylelint '**/*.css'
      - name: Run ESLint
        run: npx eslint '**/*.js'
