name: Node.js CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  html-css-js-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Ensure htmlhint is executable
        run: chmod +x ./node_modules/.bin/htmlhint
      - name: Run HTMLHint
        run: npx htmlhint '**/*.html'
      - name: Ensure stylelint is executable
        run: chmod +x ./node_modules/.bin/stylelint
      - name: Run Stylelint
        run: npx stylelint '**/*.css'
      
