name: Node.js CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  html-css-js-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run HTMLHint
        uses: Cyb3r-Jak3/htmlhint-action@v1
        with:
          files: '**/*.html'
      - name: Run Stylelint
        uses: stylelint/stylelint-action@v5
        with:
          files: '**/*.css'
      - name: Run ESLint
        uses: reviewdog/action-eslint@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          eslint_flags: '**/*.js'
